#!/bin/bash
grep -rn --exclude-dir={node_modules,.git} --exclude="package*" --exclude-dir="dist" --exclude-dir="lib" --exclude-dir="bin" --exclude="jquery*" --exclude="*min*" --exclude="DBModel" "$1" . --color;

